### ISSUE TITLE
Gradient w.r.t. an Array (Tensor)

### ISSUE THREAD

**Issue by adtzlr** [mtitze/njet#11]
Hi @mtitze,

do you think that this is the recommended way to use `njet` on many 3x3 tensors? I took the strain energy function of a [Neo-Hookean solid](https://en.wikipedia.org/wiki/Neo-Hookean_solid) as an example.

```python
from njet.functions import log
from njet import derive
import numpy as np

# init `n` random 3x3 tensors
n = 2 ** 18
x = (np.eye(3) + np.random.rand(n, 3, 3) / 10).T

def grad(fun):
    "A decorator to evaluate the gradient."
    
    def inner(x, **kwargs):
        # init the output
        out = np.zeros((9, *x.shape[2:]))
        
        # obtain the gradient and loop over items
        for key, value in fun.grad(*flatten(x), **kwargs).items():
            out[key] = value
        
        # reshape the gradient
        return out.reshape(3, 3, -1)
    
    return inner

def hess(fun):
    "A decorator to evaluate the hessian."

    def inner(x, **kwargs):
        # init the output
        out = np.zeros((9, 9, *x.shape[2:]))
        
        # obtain the hessian and loop over items
        for key, value in fun.hess(*flatten(x), **kwargs).items():
            out[key] = value
        
        # reshape the hessian
        return out.reshape(3, 3, 3, 3, -1)
    
    return inner

def trace(x):
    return x[0][0] + x[1][1] + x[2][2]

def det(x):
    a = x[0][0] * x[1][1] * x[2][2]
    b = x[0][1] * x[1][2] * x[2][0]
    c = x[0][2] * x[1][0] * x[2][1]
    d = x[2][0] * x[1][1] * x[0][2]
    e = x[2][1] * x[1][2] * x[0][0]
    f = x[2][2] * x[1][0] * x[0][1]
    return a + b + c - d - e - f

flatten = lambda x: x.reshape(9, -1)
reshape = lambda x: [[x[0], x[1], x[2]], [x[3], x[4], x[5]], [x[6], x[7], x[8]]]
# reshape = lambda x: np.array(x, dtype=object).reshape(3, 3, -1) # this fails

def tensorjet(fun):
    "A decorator to reshape the input."
    def inner(*x, **kwargs):
        return fun(reshape(x), **kwargs)
    return inner

@tensorjet
def fun(C):
    "The Neo-Hookean material formulation (isotropic hyperelasticity)."
    return trace(C) - log(det(C))

dfun = derive(fun, order=2, n_args=9)
dfundx = grad(dfun)(x)
d2fundx2 = hess(dfun)(x)

# %timeit hess(dfun)(x)
# 2.08 s ± 27.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

Any chance to use NumPy instead of nested lists, i.e. replace the reshape-method?

```python
 reshape = lambda x: np.array(x, dtype=object).reshape(3, 3, -1) # (this fails)
```

I couldn't get it to work.

Thanks!

**Comment by adtzlr** [comment]
P.S.: If you're interested how fast `njet` is for that kind of problem: I wrote a very basic benchmark on exactly that example for my package [`tensortrax`](https://github.com/adtzlr/tensortrax) and the hessian evaluation time for 2^18 tensors of 2 seconds for `njet` is between the runtimes of `tensortrax` and `autograd`. 

(By taking care of the symmetry ([Voigt](https://en.wikipedia.org/wiki/Voigt_notation) or triu-notation), `njet`'s hessian runtime may be reduced to ~1s)

**Comment by mtitze** [comment]
Hi @adtzlr,

many thanks for pointing out that issue to me! I seems that the issue are that slicing currently is not propagated by jets/jetpolys to their entries. I have not looked deep into that issue now (its late here) but for this purpose I have created a new branch 'projections' where I have changed this behavior.

Now I can run cases like this:
```
f1 = lambda *z: z[0] + z[1]
df1 = derive(f1, n_args=2, order=3)
df1(np.array([2, 1]), np.array([2, 8]))
{(0, 0): array([4, 9]), (1, 0): array([1., 1.]), (0, 1): array([1., 1.])}
```
And even cases where z is considered as a single object, e.g.:
```
f2 = lambda z: z[0] + z[1]
df2 = derive(f2, n_args=1, order=3)
df2(np.array([2, 1]))
{(0,): 3, (1,): 2.0}
```
I am, however, not yet sure if that makes sense, as I am here just varying every component with the same parameter. Probably one need to have more control about what components of the tensor should vary. This can be done in principle by modifying the njet.ad.derive.jet_input function properly.  Concerning your problem, I suppose you need 9 directions? If you can tell me in a simplified way what you need to vary, we might be able to implement something like this.

With the recent changes I have just initiated every direction by '1's. So for example one would currently get a result like this (probably not yet what you need):
```
def trace(x):
    return x[0, 0] + x[1, 1] + x[2, 2]

def det(x):
    a = x[0, 0] * x[1, 1] * x[2, 2]
    b = x[0, 1] * x[1, 2] * x[2, 0]
    c = x[0, 2] * x[1, 0] * x[2, 1]
    d = x[2, 0] * x[1, 1] * x[0, 2]
    e = x[2, 1] * x[1, 2] * x[0, 0]
    f = x[2, 2] * x[1, 0] * x[0, 1]
    return a + b + c - d - e - f

def fun(C):
    "The Neo-Hookean material formulation (isotropic hyperelasticity)."
    return trace(C) - 2 * log(det(C))

dfun = derive(fun, order=2, n_args=1)
dfun(x)
```

**Comment by mtitze** [comment]
Two additional remarks:
1) Using jets as entries in numpy arrays is in general not advised; not only will one loose the speed, but this may also lead to unpredictable results even if it works in some cases. So one should always work the other way around: Using numpy arrays as jet entries.

2) The policy should be that a function which is used in the njet 'derive' class can also be evaluated at the given point of interest. The wrapper creates a little confusion, because "fun(x)" will throw an error (of course, it is just the wrapper, but still...).

**Comment by adtzlr** [comment]
Thank you for your detailed answers!

**Comment by mtitze** [comment]
Tank you for your report and feedback. Best wishes for your study! I have merged the projections-branch into master, updated the version and will close this issue now.
